import "server-only";

/**
 * The OIR question bank.
 *
 * Server-only, and the guard above is the point: this module holds answer keys
 * and explanations, and importing it from a client component must fail the
 * build rather than quietly ship the marks to the browser. Anything a candidate
 * is allowed to see comes out of `toCandidateFacingItem`, never from here.
 *
 * The bank is read from the ingestion tool's output rather than hand-written.
 * That output is produced by `tools/oir-ingest/extract-set.mjs`, which omits any
 * question it cannot recover whole, so each file is already a verified subset:
 * Set 01 contributes 46 of the source's 50, Set 02 contributes 45 and Set 03
 * contributes 43, for 134 across the combined bank. The sixteen that are
 * missing are recorded, with reasons, in `omissionsForSet` — never in the
 * served questions.
 *
 * Loading revalidates everything anyway. The file is build output, and build
 * output can be regenerated by a future version of a tool with a new bug; a
 * bank that trusted it would serve an ungradable question the first time that
 * happened.
 */
import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";

import type { ChoiceOption, OirQuestionItem } from "@/lib/assessment/content";
import type { MediaAsset } from "@/lib/assessment/media";
import { isMediaReference } from "@/lib/assessment/media";
import {
  isAnswerKeyResolvable,
  modalityOf,
  OIR_ANSWER_KEY_KINDS,
  type OirAnswerKey,
  type OirCuration,
  type OirFigureRef,
  type OirOmission,
  type OirOptionSource,
  type OirResponseFormat,
} from "@/lib/assessment/oir/types";
import {
  contentItemId,
  isServable,
  mediaAssetId,
  type ContentProvenance,
  type ContentStatus,
  type MediaAssetId,
} from "@/lib/assessment/types";

/** Alt text is authored by a person, never generated from the picture. */
const ALT_TEXT_PLACEHOLDER_PREFIX = "Figure not yet described:";
const MIN_CURATION_EVIDENCE = 40;

class OirBankError extends Error {}

function invalid(message: string): never {
  // Bank content is authored, never candidate data, so quoting it here is safe.
  throw new OirBankError(`OIR bank: ${message}`);
}

/**
 * Where the ingested content lives.
 *
 * The tool writes to `content/` at the repository root, beside `docs/` and
 * `tools/`, so the same tree serves every app that might later read it. Next
 * runs with the frontend as its working directory, hence the step upward; the
 * plain path is tried too so the loader keeps working if the content is ever
 * vendored into the app.
 */
export function oirContentRoot(): string {
  const candidates = [
    join(process.cwd(), "..", "content", "oir"),
    join(process.cwd(), "content", "oir"),
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) return resolve(candidate);
  }
  return invalid(
    `the content root was not found. Run "node tools/oir-ingest/extract-set.mjs --set 1" ` +
      `to produce it. Looked in: ${candidates.join(", ")}`,
  );
}

export const oirSetSlug = (setNumber: number): string =>
  `set-${String(setNumber).padStart(2, "0")}`;

/**
 * The sets that have been ingested and verified, in order.
 *
 * One list, exported, because "which sets exist" was previously written out
 * separately in the attempt service and in two routes, and three copies of a
 * fact is three chances for a set to be ingested and then silently ignored by
 * one of them.
 */
export const OIR_SETS: readonly number[] = [1, 2, 3];

/**
 * The block of the global id sequence a set owns.
 *
 * There is ONE id space across the whole book — `oir.NNNN` — and each set owns
 * a contiguous block of it `sourceQuestionCount` wide, starting where the
 * previous set's block ended. Set 01 owns 1..50 and Set 02 owns 51..100, which
 * is exactly what `SET_ID_START` in `tools/oir-ingest/extract-set.mjs`
 * allocates; this is the same rule stated as an interval rather than as a
 * table, so a third set needs no edit here.
 *
 * Checking the block rather than the individual number is what makes global
 * uniqueness structural. Ids drawn from disjoint blocks cannot collide, so the
 * combined bank does not have to hope that two sets happened not to overlap —
 * and an ingest tool that regressed to per-set numbering is caught on load
 * rather than after a candidate has been served two different questions under
 * one id.
 */
function idBlockFor(
  setNumber: number,
  sourceQuestionCount: number,
): { readonly first: number; readonly last: number } {
  const first = (setNumber - 1) * sourceQuestionCount + 1;
  return { first, last: first + sourceQuestionCount - 1 };
}

/** The numeric part of an `oir.NNNN` id, or null if it is not one. */
function oirIdNumber(id: string): number | null {
  const match = /^oir\.([0-9]{4})$/.exec(id);
  return match ? Number(match[1]) : null;
}

function resolveSetFile(setNumber: number): string {
  const file = join(oirContentRoot(), oirSetSlug(setNumber), "questions.json");
  if (!existsSync(file)) {
    invalid(
      `set ${setNumber} was not found. Run ` +
        `"node tools/oir-ingest/extract-set.mjs --set ${setNumber}" to produce it.`,
    );
  }
  return file;
}

// ---------------------------------------------------------------------------
// Validation of the ingested file
// ---------------------------------------------------------------------------

type Json = Record<string, unknown>;

const asRecord = (value: unknown, what: string): Json =>
  typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Json)
    : invalid(`${what} is not an object`);

const asArray = (value: unknown, what: string): unknown[] =>
  Array.isArray(value) ? value : invalid(`${what} is not an array`);

const asString = (value: unknown, what: string): string =>
  typeof value === "string" ? value : invalid(`${what} is not a string`);

const asNumber = (value: unknown, what: string): number =>
  typeof value === "number" && Number.isFinite(value)
    ? value
    : invalid(`${what} is not a finite number`);

function parseAnswerKey(value: unknown, what: string): OirAnswerKey {
  const record = asRecord(value, what);
  const kind = asString(record.kind, `${what}.kind`);
  if (!OIR_ANSWER_KEY_KINDS.includes(kind as OirAnswerKey["kind"])) {
    invalid(`${what}.kind is ${JSON.stringify(kind)}, which is not a known answer form`);
  }
  switch (kind) {
    case "single-option": {
      const optionId = asString(record.optionId, `${what}.optionId`);
      const label = record.label === undefined ? undefined : asString(record.label, `${what}.label`);
      return label === undefined ? { kind, optionId } : { kind, optionId, label };
    }
    case "multiple-options": {
      const ids = asArray(record.optionIds, `${what}.optionIds`).map((id, i) =>
        asString(id, `${what}.optionIds[${i}]`),
      );
      if (ids.length < 2) invalid(`${what} selects fewer than two options`);
      return { kind, optionIds: ids };
    }
    case "ordered-sequence":
    case "multi-token": {
      const values = asArray(record.values, `${what}.values`).map((v, i) =>
        asString(v, `${what}.values[${i}]`),
      );
      if (values.length === 0) invalid(`${what} has no values`);
      return { kind, values };
    }
    case "short-text": {
      const value_ = asString(record.value, `${what}.value`);
      if (value_.length === 0) invalid(`${what} is empty`);
      return { kind, value: value_ };
    }
    case "boolean": {
      if (typeof record.value !== "boolean") invalid(`${what}.value is not a boolean`);
      return { kind, value: record.value };
    }
    default:
      return invalid(`${what}.kind ${JSON.stringify(kind)} is unhandled`);
  }
}

/** Bounds a written answer's shape, so a corrupt file cannot ask for 900 boxes. */
const MAX_RESPONSE_VALUES = 8;
const MAX_RESPONSE_TEXT_LENGTH = 64;

function parseResponseFormat(value: unknown, what: string): OirResponseFormat | null {
  if (value === null || value === undefined) return null;
  const record = asRecord(value, what);
  const kind = asString(record.kind, `${what}.kind`);

  if (kind === "single-option" || kind === "boolean") return { kind };
  if (kind === "multiple-options") {
    const count = asNumber(record.count, `${what}.count`);
    if (!Number.isInteger(count) || count < 2 || count > MAX_RESPONSE_VALUES) {
      invalid(`${what}.count is not a usable number of selections`);
    }
    return { kind, count };
  }
  if (kind === "short-text") {
    const maxLength = asNumber(record.maxLength, `${what}.maxLength`);
    if (!Number.isInteger(maxLength) || maxLength < 1 || maxLength > MAX_RESPONSE_TEXT_LENGTH) {
      invalid(`${what}.maxLength is not a usable length`);
    }
    return { kind, maxLength };
  }
  if (kind === "multi-token" || kind === "ordered-sequence") {
    const count = asNumber(record.count, `${what}.count`);
    if (!Number.isInteger(count) || count < 1 || count > MAX_RESPONSE_VALUES) {
      invalid(`${what}.count is not a usable number of values`);
    }
    return { kind, count };
  }
  return invalid(`${what}.kind is ${JSON.stringify(kind)}, which is not a written answer shape`);
}

function parseStatus(value: unknown, what: string): ContentStatus {
  const status = asString(value, what);
  if (status !== "draft" && status !== "active" && status !== "retired") {
    invalid(`${what} is ${JSON.stringify(status)}, which is not a lifecycle state`);
  }
  return status;
}

type OriginalProvenance = Extract<ContentProvenance, { kind: "original" }>;

function parseProvenance(value: unknown, what: string): OriginalProvenance {
  const record = asRecord(value, what);
  const kind = asString(record.kind, `${what}.kind`);
  if (kind !== "original") {
    // The only provenance this bank is built for. Anything else is a change
    // someone must make deliberately, not something to be waved through.
    invalid(`${what}.kind is ${JSON.stringify(kind)}; this bank only carries original content`);
  }
  return {
    kind: "original",
    author: asString(record.author, `${what}.author`),
    createdAt: asString(record.createdAt, `${what}.createdAt`),
  };
}

function parseOptions(value: unknown, what: string): ChoiceOption[] {
  const options = asArray(value, what).map((option, i) => {
    const record = asRecord(option, `${what}[${i}]`);
    return {
      id: asString(record.id, `${what}[${i}].id`),
      text: asString(record.text, `${what}[${i}].text`),
    };
  });
  const ids = new Set(options.map((option) => option.id));
  if (ids.size !== options.length) invalid(`${what} has duplicate option ids`);
  return options;
}

function parseCurations(value: unknown, what: string): OirCuration[] {
  return asArray(value, what).map((entry, i) => {
    const record = asRecord(entry, `${what}[${i}]`);
    const field = asString(record.field, `${what}[${i}].field`);
    if (field !== "answerKey" && field !== "pictorialOptions") {
      invalid(`${what}[${i}].field ${JSON.stringify(field)} is not curatable`);
    }
    const evidence = asString(record.evidence, `${what}[${i}].evidence`);
    if (evidence.trim().length < MIN_CURATION_EVIDENCE) {
      invalid(`${what}[${i}] cites no substantive evidence`);
    }
    return { field, evidence };
  });
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

export interface OirSet {
  readonly setNumber: number;
  readonly questions: readonly OirQuestionItem[];
  readonly media: ReadonlyMap<MediaAssetId, MediaAsset>;
  readonly omissions: readonly OirOmission[];
  /** How many questions the source book contains, omissions included. */
  readonly sourceQuestionCount: number;
}

const cache = new Map<number, OirSet>();

function loadSet(setNumber: number): OirSet {
  const raw = asRecord(JSON.parse(readFileSync(resolveSetFile(setNumber), "utf8")), "file");
  if (asNumber(raw.setNumber, "setNumber") !== setNumber) {
    invalid(`file for set ${setNumber} declares set ${String(raw.setNumber)}`);
  }
  const setProvenance = parseProvenance(raw.provenance, "provenance");
  const slug = oirSetSlug(setNumber);
  // Read before the questions are walked: it fixes this set's id block, and an
  // id has to be checked against that block as it is parsed.
  const sourceQuestionCount = asNumber(raw.sourceQuestionCount, "sourceQuestionCount");
  const idBlock = idBlockFor(setNumber, sourceQuestionCount);
  const seenIds = new Set<string>();

  const media = new Map<MediaAssetId, MediaAsset>();
  const questions: OirQuestionItem[] = [];
  const seenPositions = new Set<number>();

  for (const [index, entry] of asArray(raw.questions, "questions").entries()) {
    const record = asRecord(entry, `questions[${index}]`);
    const where = `questions[${index}]`;
    const position = asNumber(record.position, `${where}.position`);
    if (seenPositions.has(position)) invalid(`${where} repeats position ${position}`);
    seenPositions.add(position);

    if (!Number.isInteger(position) || position < 1 || position > sourceQuestionCount) {
      invalid(`${where}.position ${position} is not a position in a ${sourceQuestionCount}-question set`);
    }

    const id = contentItemId(asString(record.id, `${where}.id`));
    // Checked against the set's allocated block, NOT against the position.
    //
    // Set 01 allocates its ids by source position and Set 02 allocates them
    // sequentially over accepted records, so `id === position` holds for the
    // first set and for no other. It was the rule here while Set 01 was the
    // only set, which made Set 02 unloadable: `oir.0051` at position 1 is
    // correct under the scheme the ingest tool froze, and was rejected here as
    // a mismatch. The block is the invariant both allocations actually share.
    const idNumber = oirIdNumber(id);
    if (idNumber === null) {
      return invalid(`${where}.id ${JSON.stringify(id)} is not an "oir.NNNN" id`);
    }
    if (idNumber < idBlock.first || idNumber > idBlock.last) {
      invalid(
        `${where}.id ${JSON.stringify(id)} falls outside set ${setNumber}'s allocated id block ` +
          `oir.${String(idBlock.first).padStart(4, "0")}..oir.${String(idBlock.last).padStart(4, "0")}`,
      );
    }
    if (seenIds.has(id)) invalid(`${where}.id ${JSON.stringify(id)} is used twice`);
    seenIds.add(id);
    if (asString(record.type, `${where}.type`) !== "oir-question") {
      invalid(`${where}.type is not "oir-question"`);
    }

    const stem = asString(record.stem, `${where}.stem`);
    const options = parseOptions(record.options, `${where}.options`);
    const optionSource = asString(record.optionSource, `${where}.optionSource`) as OirOptionSource;
    if (optionSource !== "text" && optionSource !== "figure" && optionSource !== "none") {
      invalid(`${where}.optionSource ${JSON.stringify(optionSource)} is not a known source`);
    }
    const pictorialOptionIds = asArray(record.pictorialOptionIds, `${where}.pictorialOptionIds`).map(
      (id, i) => asString(id, `${where}.pictorialOptionIds[${i}]`),
    );
    if (new Set(pictorialOptionIds).size !== pictorialOptionIds.length) {
      invalid(`${where}.pictorialOptionIds repeats a label`);
    }
    if (pictorialOptionIds.some((id) => !/^[0-9]{1,2}$/.test(id))) {
      invalid(`${where}.pictorialOptionIds holds something that is not a numbered choice`);
    }
    const responseFormat = parseResponseFormat(record.responseFormat, `${where}.responseFormat`);
    if (responseFormat === null) invalid(`${where}.responseFormat is missing`);
    // Every question declares how it is answered, and that declaration has to
    // agree with where its choices come from: a question answered by choosing
    // must offer choices, and one answered by writing must not.
    const choosesOption =
      responseFormat.kind === "single-option" || responseFormat.kind === "multiple-options";
    if (choosesOption === (optionSource === "none")) {
      invalid(
        `${where}.optionSource says "${optionSource}" but its response format is ` +
          `"${responseFormat.kind}", which does not match how the question is answered.`,
      );
    }
    if ((optionSource === "figure") !== pictorialOptionIds.length > 0) {
      invalid(`${where}.optionSource says "${optionSource}" but ${pictorialOptionIds.length} pictorial choices are recorded`);
    }
    if ((optionSource === "text") !== options.length > 0) {
      invalid(`${where}.optionSource says "${optionSource}" but ${options.length} options are printed`);
    }

    const figures: OirFigureRef[] = asArray(record.figures, `${where}.figures`).map(
      (reference, figureIndex) => {
        const path = asString(reference, `${where}.figures[${figureIndex}]`);
        if (!isMediaReference(path)) {
          invalid(`${where}.figures[${figureIndex}] ${JSON.stringify(path)} is not a safe media reference`);
        }
        if (!path.startsWith(`oir/${slug}/figures/`)) {
          invalid(`${where}.figures[${figureIndex}] points outside this set's figure directory`);
        }
        // Derived from the GLOBAL question id, not from `position`. Position is
        // per-set, so position-derived figure ids collided across sets — Set 01
        // question 1 and Set 02 question 1 both claimed `oir-figure.00011` —
        // and a combined bank would have served one set's diagram under the
        // other set's id. Set 01's figure ids are unchanged by this, because
        // its id number and its position are the same number.
        const assetId = mediaAssetId(
          `oir-figure.${String(idNumber).padStart(4, "0")}${String(figureIndex + 1)}`,
        );
        media.set(assetId, {
          id: assetId,
          kind: "image",
          reference: path,
          mimeType: "image/png",
          // Deliberately a placeholder. Describing a reasoning diagram without
          // having seen it would put a candidate who relies on alt text in
          // front of a different question from everyone else.
          altText: `${ALT_TEXT_PLACEHOLDER_PREFIX} diagram ${figureIndex + 1} for OIR set ${setNumber} question ${position}.`,
          width: null,
          height: null,
          isIntentionallyIndistinct: false,
          status: "active",
          provenance: setProvenance,
          addedAt: setProvenance.createdAt,
        });
        return { mediaId: assetId, order: figureIndex + 1, needsAltText: true };
      },
    );

    if (stem.length === 0 && figures.length === 0) {
      invalid(`${where} has neither a stem nor a figure`);
    }

    const answerKey = parseAnswerKey(record.answerKey, `${where}.answerKey`);
    const sourcePagesRecord = asRecord(record.sourcePages, `${where}.sourcePages`);
    const explanation = record.explanation === null ? null : asString(record.explanation, `${where}.explanation`);

    const question: OirQuestionItem = {
      id,
      type: "oir-question",
      usedBy: ["oir"],
      version: asNumber(record.version, `${where}.version`),
      // Read, not assumed. Hard-coding "active" here would have made the
      // servability check below unfalsifiable.
      status: parseStatus(record.status, `${where}.status`),
      provenance: parseProvenance(record.provenance, `${where}.provenance`),
      tags: asArray(record.tags, `${where}.tags`).map((tag, i) => asString(tag, `${where}.tags[${i}]`)),
      difficulty: null,
      authoredAt: asString(record.authoredAt, `${where}.authoredAt`),
      editorialNote: record.editorialNote === null ? null : asString(record.editorialNote, `${where}.editorialNote`),
      stem,
      options,
      optionSource,
      pictorialOptionIds,
      responseFormat,
      figures,
      modality: modalityOf({ figures }),
      answerKey,
      explanation,
      setNumber,
      position,
      sourcePages: {
        question: asNumber(sourcePagesRecord.question, `${where}.sourcePages.question`),
        answer: asNumber(sourcePagesRecord.answer, `${where}.sourcePages.answer`),
      },
      curations: parseCurations(record.curations, `${where}.curations`),
    };

    // The two invariants that make a question servable at all: it may be shown,
    // and its answer can be resolved against what it shows.
    if (!isServable(question)) invalid(`${id} is not servable`);
    if (!isAnswerKeyResolvable(question)) {
      invalid(`${id} has an answer key that cannot be resolved against its options or figures`);
    }
    questions.push(question);
  }

  const omissions: OirOmission[] = asArray(raw.omitted, "omitted").map((entry, i) => {
    const record = asRecord(entry, `omitted[${i}]`);
    const pages = asRecord(record.sourcePages, `omitted[${i}].sourcePages`);
    const reasons = asArray(record.reasons, `omitted[${i}].reasons`).map((reason, j) =>
      asString(reason, `omitted[${i}].reasons[${j}]`),
    );
    if (reasons.length === 0) invalid(`omitted[${i}] records no reason`);
    return {
      position: asNumber(record.position, `omitted[${i}].position`),
      reasons,
      sourcePages: {
        question: asNumber(pages.question, `omitted[${i}].sourcePages.question`),
        answer: asNumber(pages.answer, `omitted[${i}].sourcePages.answer`),
      },
    };
  });

  if (questions.length + omissions.length !== sourceQuestionCount) {
    invalid(
      `${questions.length} questions plus ${omissions.length} omissions do not account for ` +
        `the ${sourceQuestionCount} questions in the source`,
    );
  }
  for (const omission of omissions) {
    if (seenPositions.has(omission.position)) {
      invalid(`position ${omission.position} is both served and omitted`);
    }
  }

  return { setNumber, questions, media, omissions, sourceQuestionCount };
}

/** Loads a set, validating it, and keeps it for the life of the process. */
export function getOirSet(setNumber: number): OirSet {
  const cached = cache.get(setNumber);
  if (cached) return cached;
  const set = loadSet(setNumber);
  cache.set(setNumber, set);
  return set;
}

export function getOirQuestion(setNumber: number, position: number): OirQuestionItem | null {
  return getOirSet(setNumber).questions.find((q) => q.position === position) ?? null;
}

export function getOirMedia(setNumber: number, id: MediaAssetId): MediaAsset | null {
  return getOirSet(setNumber).media.get(id) ?? null;
}

/** Why the source's other questions are not here. */
export function omissionsForSet(setNumber: number): readonly OirOmission[] {
  return getOirSet(setNumber).omissions;
}

// ---------------------------------------------------------------------------
// The combined bank
// ---------------------------------------------------------------------------

/**
 * Every ingested set, flattened into one bank.
 *
 * A production paper is drawn from all verified content rather than from one
 * set, so something has to hold "all of it" — and that something is the right
 * place to prove the property the whole scheme rests on: that an id means one
 * question. Set 01 alone could not test that, because a single set trivially
 * cannot collide with itself.
 *
 * Questions keep their sets' order, sets in ascending order. That is a stable
 * order, not a meaningful one: selection shuffles, and nothing downstream may
 * read significance into an index here.
 */
export interface OirBank {
  readonly sets: readonly number[];
  readonly questions: readonly OirQuestionItem[];
  readonly media: ReadonlyMap<MediaAssetId, MediaAsset>;
}

let combined: OirBank | null = null;

export function getOirBank(): OirBank {
  if (combined) return combined;

  const questions: OirQuestionItem[] = [];
  const media = new Map<MediaAssetId, MediaAsset>();
  const questionOwner = new Map<string, number>();
  const mediaOwner = new Map<string, number>();

  for (const setNumber of OIR_SETS) {
    const set = getOirSet(setNumber);
    for (const question of set.questions) {
      // The block rule in `loadSet` should already make this impossible. It is
      // asserted anyway: this is the one place the sets meet, a collision here
      // means a candidate could be served one question and marked against
      // another, and an invariant worth the scheme is worth one Map lookup.
      const previous = questionOwner.get(question.id);
      if (previous !== undefined) {
        invalid(`${question.id} is claimed by both set ${previous} and set ${setNumber}`);
      }
      questionOwner.set(question.id, setNumber);
      questions.push(question);
    }
    for (const [id, asset] of set.media) {
      const previous = mediaOwner.get(id);
      if (previous !== undefined) {
        invalid(`media ${id} is claimed by both set ${previous} and set ${setNumber}`);
      }
      mediaOwner.set(id, setNumber);
      media.set(id, asset);
    }
  }

  combined = { sets: OIR_SETS, questions, media };
  return combined;
}

/**
 * A question by its global id, from whichever set holds it.
 *
 * This is what a served paper needs: an attempt records ids, and by the time an
 * answer or a mark comes back, which set the question came from is neither
 * known nor interesting. `getOirQuestion(set, position)` remains for callers
 * that genuinely mean "this set's question N".
 */
export function getOirQuestionById(id: string): OirQuestionItem | null {
  return getOirBank().questions.find((question) => question.id === id) ?? null;
}

/** A figure by its global media id, from whichever set holds it. */
export function getOirMediaById(id: MediaAssetId): MediaAsset | null {
  return getOirBank().media.get(id) ?? null;
}

/** Test seam: forces the next call to re-read and re-validate from disk. */
export function clearOirBankCache(): void {
  cache.clear();
  combined = null;
}
