import "server-only";

/**
 * The OIR question bank.
 *
 * Server-only, and the guard above is the point: this module holds answer keys
 * and explanations, and importing it from a client component must fail the
 * build rather than quietly ship the marks to the browser. Anything a candidate
 * is allowed to see comes out of `toCandidateFacingItem`, never from here.
 *
 * The bank is read from the ingestion tool's output rather than hand-written.
 * That output is produced by `tools/oir-ingest/extract-set.mjs`, which omits any
 * question it cannot recover whole, so the file is already a verified subset:
 * Set 01 contributes 46 of the source's 50. The four that are missing are
 * recorded, with reasons, in `omissionsForSet`.
 *
 * Loading revalidates everything anyway. The file is build output, and build
 * output can be regenerated by a future version of a tool with a new bug; a
 * bank that trusted it would serve an ungradable question the first time that
 * happened.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { ChoiceOption, OirQuestionItem } from "@/lib/assessment/content";
import type { MediaAsset } from "@/lib/assessment/media";
import { isMediaReference } from "@/lib/assessment/media";
import {
  isAnswerKeyResolvable,
  modalityOf,
  OIR_ANSWER_KEY_KINDS,
  type OirAnswerKey,
  type OirCuration,
  type OirFigureRef,
  type OirOmission,
  type OirOptionSource,
} from "@/lib/assessment/oir/types";
import {
  contentItemId,
  isServable,
  mediaAssetId,
  type ContentProvenance,
  type ContentStatus,
  type MediaAssetId,
} from "@/lib/assessment/types";

/** Alt text is authored by a person, never generated from the picture. */
const ALT_TEXT_PLACEHOLDER_PREFIX = "Figure not yet described:";
const MIN_CURATION_EVIDENCE = 40;

class OirBankError extends Error {}

function invalid(message: string): never {
  // Bank content is authored, never candidate data, so quoting it here is safe.
  throw new OirBankError(`OIR bank: ${message}`);
}

/**
 * Where the ingested content lives.
 *
 * The tool writes to `content/` at the repository root, beside `docs/` and
 * `tools/`, so the same tree serves every app that might later read it. Next
 * runs with the frontend as its working directory, hence the step upward; the
 * plain path is tried too so the loader keeps working if the content is ever
 * vendored into the app.
 */
function resolveSetFile(setNumber: number): string {
  const slug = `set-${String(setNumber).padStart(2, "0")}`;
  const candidates = [
    join(process.cwd(), "..", "content", "oir", slug, "questions.json"),
    join(process.cwd(), "content", "oir", slug, "questions.json"),
  ];
  for (const candidate of candidates) {
    try {
      readFileSync(candidate);
      return candidate;
    } catch {
      // Try the next location.
    }
  }
  return invalid(
    `set ${setNumber} was not found. Run "node tools/oir-ingest/extract-set.mjs --set ${setNumber}" ` +
      `to produce it. Looked in: ${candidates.join(", ")}`,
  );
}

// ---------------------------------------------------------------------------
// Validation of the ingested file
// ---------------------------------------------------------------------------

type Json = Record<string, unknown>;

const asRecord = (value: unknown, what: string): Json =>
  typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Json)
    : invalid(`${what} is not an object`);

const asArray = (value: unknown, what: string): unknown[] =>
  Array.isArray(value) ? value : invalid(`${what} is not an array`);

const asString = (value: unknown, what: string): string =>
  typeof value === "string" ? value : invalid(`${what} is not a string`);

const asNumber = (value: unknown, what: string): number =>
  typeof value === "number" && Number.isFinite(value)
    ? value
    : invalid(`${what} is not a finite number`);

function parseAnswerKey(value: unknown, what: string): OirAnswerKey {
  const record = asRecord(value, what);
  const kind = asString(record.kind, `${what}.kind`);
  if (!OIR_ANSWER_KEY_KINDS.includes(kind as OirAnswerKey["kind"])) {
    invalid(`${what}.kind is ${JSON.stringify(kind)}, which is not a known answer form`);
  }
  switch (kind) {
    case "single-option": {
      const optionId = asString(record.optionId, `${what}.optionId`);
      const label = record.label === undefined ? undefined : asString(record.label, `${what}.label`);
      return label === undefined ? { kind, optionId } : { kind, optionId, label };
    }
    case "multiple-options": {
      const ids = asArray(record.optionIds, `${what}.optionIds`).map((id, i) =>
        asString(id, `${what}.optionIds[${i}]`),
      );
      if (ids.length < 2) invalid(`${what} selects fewer than two options`);
      return { kind, optionIds: ids };
    }
    case "ordered-sequence":
    case "multi-token": {
      const values = asArray(record.values, `${what}.values`).map((v, i) =>
        asString(v, `${what}.values[${i}]`),
      );
      if (values.length === 0) invalid(`${what} has no values`);
      return { kind, values };
    }
    case "short-text": {
      const value_ = asString(record.value, `${what}.value`);
      if (value_.length === 0) invalid(`${what} is empty`);
      return { kind, value: value_ };
    }
    case "boolean": {
      if (typeof record.value !== "boolean") invalid(`${what}.value is not a boolean`);
      return { kind, value: record.value };
    }
    default:
      return invalid(`${what}.kind ${JSON.stringify(kind)} is unhandled`);
  }
}

function parseStatus(value: unknown, what: string): ContentStatus {
  const status = asString(value, what);
  if (status !== "draft" && status !== "active" && status !== "retired") {
    invalid(`${what} is ${JSON.stringify(status)}, which is not a lifecycle state`);
  }
  return status;
}

type OriginalProvenance = Extract<ContentProvenance, { kind: "original" }>;

function parseProvenance(value: unknown, what: string): OriginalProvenance {
  const record = asRecord(value, what);
  const kind = asString(record.kind, `${what}.kind`);
  if (kind !== "original") {
    // The only provenance this bank is built for. Anything else is a change
    // someone must make deliberately, not something to be waved through.
    invalid(`${what}.kind is ${JSON.stringify(kind)}; this bank only carries original content`);
  }
  return {
    kind: "original",
    author: asString(record.author, `${what}.author`),
    createdAt: asString(record.createdAt, `${what}.createdAt`),
  };
}

function parseOptions(value: unknown, what: string): ChoiceOption[] {
  const options = asArray(value, what).map((option, i) => {
    const record = asRecord(option, `${what}[${i}]`);
    return {
      id: asString(record.id, `${what}[${i}].id`),
      text: asString(record.text, `${what}[${i}].text`),
    };
  });
  const ids = new Set(options.map((option) => option.id));
  if (ids.size !== options.length) invalid(`${what} has duplicate option ids`);
  return options;
}

function parseCurations(value: unknown, what: string): OirCuration[] {
  return asArray(value, what).map((entry, i) => {
    const record = asRecord(entry, `${what}[${i}]`);
    const field = asString(record.field, `${what}[${i}].field`);
    if (field !== "answerKey") invalid(`${what}[${i}].field ${JSON.stringify(field)} is not curatable`);
    const evidence = asString(record.evidence, `${what}[${i}].evidence`);
    if (evidence.trim().length < MIN_CURATION_EVIDENCE) {
      invalid(`${what}[${i}] cites no substantive evidence`);
    }
    return { field, evidence };
  });
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

export interface OirSet {
  readonly setNumber: number;
  readonly questions: readonly OirQuestionItem[];
  readonly media: ReadonlyMap<MediaAssetId, MediaAsset>;
  readonly omissions: readonly OirOmission[];
  /** How many questions the source book contains, omissions included. */
  readonly sourceQuestionCount: number;
}

const cache = new Map<number, OirSet>();

function loadSet(setNumber: number): OirSet {
  const raw = asRecord(JSON.parse(readFileSync(resolveSetFile(setNumber), "utf8")), "file");
  if (asNumber(raw.setNumber, "setNumber") !== setNumber) {
    invalid(`file for set ${setNumber} declares set ${String(raw.setNumber)}`);
  }
  const setProvenance = parseProvenance(raw.provenance, "provenance");
  const slug = `set-${String(setNumber).padStart(2, "0")}`;

  const media = new Map<MediaAssetId, MediaAsset>();
  const questions: OirQuestionItem[] = [];
  const seenPositions = new Set<number>();

  for (const [index, entry] of asArray(raw.questions, "questions").entries()) {
    const record = asRecord(entry, `questions[${index}]`);
    const where = `questions[${index}]`;
    const position = asNumber(record.position, `${where}.position`);
    if (seenPositions.has(position)) invalid(`${where} repeats position ${position}`);
    seenPositions.add(position);

    const id = contentItemId(asString(record.id, `${where}.id`));
    if (id !== `oir.${String(position).padStart(4, "0")}`) {
      invalid(`${where}.id ${JSON.stringify(id)} does not match position ${position}`);
    }
    if (asString(record.type, `${where}.type`) !== "oir-question") {
      invalid(`${where}.type is not "oir-question"`);
    }

    const stem = asString(record.stem, `${where}.stem`);
    const options = parseOptions(record.options, `${where}.options`);
    const optionSource = asString(record.optionSource, `${where}.optionSource`) as OirOptionSource;
    if (optionSource !== "text" && optionSource !== "figure" && optionSource !== "none") {
      invalid(`${where}.optionSource ${JSON.stringify(optionSource)} is not a known source`);
    }
    if ((optionSource === "text") !== options.length > 0) {
      invalid(`${where}.optionSource says "${optionSource}" but ${options.length} options are printed`);
    }

    const figures: OirFigureRef[] = asArray(record.figures, `${where}.figures`).map(
      (reference, figureIndex) => {
        const path = asString(reference, `${where}.figures[${figureIndex}]`);
        if (!isMediaReference(path)) {
          invalid(`${where}.figures[${figureIndex}] ${JSON.stringify(path)} is not a safe media reference`);
        }
        if (!path.startsWith(`oir/${slug}/figures/`)) {
          invalid(`${where}.figures[${figureIndex}] points outside this set's figure directory`);
        }
        const assetId = mediaAssetId(
          `oir-figure.${String(position).padStart(4, "0")}${String(figureIndex + 1)}`,
        );
        media.set(assetId, {
          id: assetId,
          kind: "image",
          reference: path,
          mimeType: "image/png",
          // Deliberately a placeholder. Describing a reasoning diagram without
          // having seen it would put a candidate who relies on alt text in
          // front of a different question from everyone else.
          altText: `${ALT_TEXT_PLACEHOLDER_PREFIX} diagram ${figureIndex + 1} for OIR set ${setNumber} question ${position}.`,
          width: null,
          height: null,
          isIntentionallyIndistinct: false,
          status: "active",
          provenance: setProvenance,
          addedAt: setProvenance.createdAt,
        });
        return { mediaId: assetId, order: figureIndex + 1, needsAltText: true };
      },
    );

    if (stem.length === 0 && figures.length === 0) {
      invalid(`${where} has neither a stem nor a figure`);
    }

    const answerKey = parseAnswerKey(record.answerKey, `${where}.answerKey`);
    const sourcePagesRecord = asRecord(record.sourcePages, `${where}.sourcePages`);
    const explanation = record.explanation === null ? null : asString(record.explanation, `${where}.explanation`);

    const question: OirQuestionItem = {
      id,
      type: "oir-question",
      usedBy: ["oir"],
      version: asNumber(record.version, `${where}.version`),
      // Read, not assumed. Hard-coding "active" here would have made the
      // servability check below unfalsifiable.
      status: parseStatus(record.status, `${where}.status`),
      provenance: parseProvenance(record.provenance, `${where}.provenance`),
      tags: asArray(record.tags, `${where}.tags`).map((tag, i) => asString(tag, `${where}.tags[${i}]`)),
      difficulty: null,
      authoredAt: asString(record.authoredAt, `${where}.authoredAt`),
      editorialNote: record.editorialNote === null ? null : asString(record.editorialNote, `${where}.editorialNote`),
      stem,
      options,
      optionSource,
      figures,
      modality: modalityOf({ figures }),
      answerKey,
      explanation,
      setNumber,
      position,
      sourcePages: {
        question: asNumber(sourcePagesRecord.question, `${where}.sourcePages.question`),
        answer: asNumber(sourcePagesRecord.answer, `${where}.sourcePages.answer`),
      },
      curations: parseCurations(record.curations, `${where}.curations`),
    };

    // The two invariants that make a question servable at all: it may be shown,
    // and its answer can be resolved against what it shows.
    if (!isServable(question)) invalid(`${id} is not servable`);
    if (!isAnswerKeyResolvable(question)) {
      invalid(`${id} has an answer key that cannot be resolved against its options or figures`);
    }
    questions.push(question);
  }

  const omissions: OirOmission[] = asArray(raw.omitted, "omitted").map((entry, i) => {
    const record = asRecord(entry, `omitted[${i}]`);
    const pages = asRecord(record.sourcePages, `omitted[${i}].sourcePages`);
    const reasons = asArray(record.reasons, `omitted[${i}].reasons`).map((reason, j) =>
      asString(reason, `omitted[${i}].reasons[${j}]`),
    );
    if (reasons.length === 0) invalid(`omitted[${i}] records no reason`);
    return {
      position: asNumber(record.position, `omitted[${i}].position`),
      reasons,
      sourcePages: {
        question: asNumber(pages.question, `omitted[${i}].sourcePages.question`),
        answer: asNumber(pages.answer, `omitted[${i}].sourcePages.answer`),
      },
    };
  });

  const sourceQuestionCount = asNumber(raw.sourceQuestionCount, "sourceQuestionCount");
  if (questions.length + omissions.length !== sourceQuestionCount) {
    invalid(
      `${questions.length} questions plus ${omissions.length} omissions do not account for ` +
        `the ${sourceQuestionCount} questions in the source`,
    );
  }
  for (const omission of omissions) {
    if (seenPositions.has(omission.position)) {
      invalid(`position ${omission.position} is both served and omitted`);
    }
  }

  return { setNumber, questions, media, omissions, sourceQuestionCount };
}

/** Loads a set, validating it, and keeps it for the life of the process. */
export function getOirSet(setNumber: number): OirSet {
  const cached = cache.get(setNumber);
  if (cached) return cached;
  const set = loadSet(setNumber);
  cache.set(setNumber, set);
  return set;
}

export function getOirQuestion(setNumber: number, position: number): OirQuestionItem | null {
  return getOirSet(setNumber).questions.find((q) => q.position === position) ?? null;
}

export function getOirMedia(setNumber: number, id: MediaAssetId): MediaAsset | null {
  return getOirSet(setNumber).media.get(id) ?? null;
}

/** Why the source's other questions are not here. */
export function omissionsForSet(setNumber: number): readonly OirOmission[] {
  return getOirSet(setNumber).omissions;
}

/** Test seam: forces the next call to re-read and re-validate from disk. */
export function clearOirBankCache(): void {
  cache.clear();
}
